apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: TUhEeGtEMUNMMzZjczJNTWxEM2RJc0tyQmdQaThaTnptZDRMMnFiSGdUcDdoT1dwNm1salJ3YlI4d20xaENVMjFIeVhWbHVaSzIyVU9LdFZwbk5wbkwxcHlTZjl0K3NNRGhHeTJ4VlE2dkM1ego=